"""empty message

Revision ID: 0548e68f5bd7
Revises: fb620f20c2ad
Create Date: 2024-09-27 14:30:47.739478

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0548e68f5bd7"
down_revision: Union[str, None] = "fb620f20c2ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_costs_name", "costs", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_costs_name", "costs", ["name"])
    # ### end Alembic commands ###
