"""empty message

Revision ID: 0a6050da347f
Revises: ea658b49d015
Create Date: 2025-03-14 10:30:24.104562

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a6050da347f"
down_revision: Union[str, None] = "ea658b49d015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("last_notification", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("notify_cost_threshold", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notify_cost_threshold")
    op.drop_column("users", "last_notification")
    # ### end Alembic commands ###
