"""empty message

Revision ID: 582ba7eac761
Revises: 3ef6fd0f6aaf
Create Date: 2024-12-09 14:40:12.364120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "582ba7eac761"
down_revision: Union[str, None] = "3ef6fd0f6aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incomes",
        "source",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Enum("revenue", "gift", "debt", "other", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incomes",
        "source",
        existing_type=sa.Enum(
            "revenue", "gift", "debt", "other", native_enum=False
        ),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
