"""empty message

Revision ID: 5a529d616e33
Revises: 8c1cfe8e8700
Create Date: 2024-09-24 11:50:46.752456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a529d616e33"
down_revision: Union[str, None] = "8c1cfe8e8700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "token", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
