"""empty message

Revision ID: 66892f114cc0
Revises: c4952a3a5624
Create Date: 2024-09-27 15:08:52.245525

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66892f114cc0"
down_revision: Union[str, None] = "c4952a3a5624"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_incomes_category_id_cost_categories", "incomes", type_="foreignkey"
    )
    op.drop_column("incomes", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incomes",
        sa.Column(
            "category_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "fk_incomes_category_id_cost_categories",
        "incomes",
        "cost_categories",
        ["category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
