"""empty message

Revision ID: 79a0d6d194ca
Revises: cc52aac9ed5e
Create Date: 2024-12-03 21:48:51.289738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79a0d6d194ca"
down_revision: Union[str, None] = "cc52aac9ed5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "cost_snippets",
            postgresql.ARRAY(sa.Integer(), dimensions=1),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "income_snippets",
            postgresql.ARRAY(sa.Integer(), dimensions=1),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "income_snippets")
    op.drop_column("users", "cost_snippets")
    # ### end Alembic commands ###
