"""empty message

Revision ID: 8c1cfe8e8700
Revises: ec492f05e5d5
Create Date: 2024-09-24 11:49:39.488116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c1cfe8e8700"
down_revision: Union[str, None] = "ec492f05e5d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("common_costs", sa.String(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("common_incomes", sa.String(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("default_currency_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("default_cost_category_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_users_default_cost_category_id_cost_categories"),
        "users",
        "cost_categories",
        ["default_cost_category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_users_default_currency_id_currencies"),
        "users",
        "currencies",
        ["default_currency_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_default_currency_id_currencies"),
        "users",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_users_default_cost_category_id_cost_categories"),
        "users",
        type_="foreignkey",
    )
    op.drop_column("users", "default_cost_category_id")
    op.drop_column("users", "default_currency_id")
    op.drop_column("users", "common_incomes")
    op.drop_column("users", "common_costs")
    # ### end Alembic commands ###
