"""empty message

Revision ID: 8d9ab73e9165
Revises: 8ed087c0b37f
Create Date: 2024-09-27 21:37:59.371338

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d9ab73e9165"
down_revision: Union[str, None] = "8ed087c0b37f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_incomes_name", "incomes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_incomes_name", "incomes", ["name"])
    # ### end Alembic commands ###
