"""empty message

Revision ID: 8ed087c0b37f
Revises: 66892f114cc0
Create Date: 2024-09-27 15:12:19.972826

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ed087c0b37f"
down_revision: Union[str, None] = "66892f114cc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incomes_source", table_name="incomes")
    op.create_index(
        op.f("ix_incomes_source"), "incomes", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incomes_source"), table_name="incomes")
    op.create_index("ix_incomes_source", "incomes", ["source"], unique=True)
    # ### end Alembic commands ###
