"""empty message

Revision ID: 917183cf8e5f
Revises: 6100112aa980
Create Date: 2026-04-01 20:31:37.848404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "917183cf8e5f"
down_revision: Union[str, None] = "6100112aa980"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deleted_signals",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("human_feedback", sa.String(length=5000), nullable=True),
        sa.Column(
            "sources",
            postgresql.ARRAY(sa.String(), dimensions=1),
            nullable=True,
        ),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_deleted_signals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deleted_signals")),
    )
    op.create_index(
        op.f("ix_deleted_signals_created_at"),
        "deleted_signals",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deleted_signals_user_id"),
        "deleted_signals",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "news_items", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_news_items_user_id"), "news_items", ["user_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_news_items_user_id_users"),
        "news_items",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_news_items_user_id_users"), "news_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_news_items_user_id"), table_name="news_items")
    op.drop_column("news_items", "user_id")
    op.drop_index(
        op.f("ix_deleted_signals_user_id"), table_name="deleted_signals"
    )
    op.drop_index(
        op.f("ix_deleted_signals_created_at"), table_name="deleted_signals"
    )
    op.drop_table("deleted_signals")
    # ### end Alembic commands ###
