"""empty message

Revision ID: a125e6ac95d6
Revises: e718179ea572
Create Date: 2026-01-26 18:22:21.843425

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a125e6ac95d6"
down_revision: Union[str, None] = "e718179ea572"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password_hash", sa.String(length=255), nullable=True),
    )
    op.drop_constraint(op.f("uq_users_token"), "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        op.f("uq_users_token"),
        "users",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
