"""empty message

Revision ID: b6f2c5d8783b
Revises: 0a6050da347f
Create Date: 2025-06-04 08:58:44.530704

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6f2c5d8783b"
down_revision: Union[str, None] = "0a6050da347f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("monobank_api_key", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "monobank_api_key")
    # ### end Alembic commands ###
