"""empty message

Revision ID: c4952a3a5624
Revises: 5808057ca17e
Create Date: 2024-09-27 14:55:15.780655

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4952a3a5624"
down_revision: Union[str, None] = "5808057ca17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "costs",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchanges",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "incomes",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DATE(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "incomes",
        "timestamp",
        existing_type=sa.DATE(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "exchanges",
        "timestamp",
        existing_type=sa.DATE(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "costs",
        "timestamp",
        existing_type=sa.DATE(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###
