"""empty message

Revision ID: e718179ea572
Revises: b6f2c5d8783b
Create Date: 2025-07-11 09:51:27.063332

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e718179ea572"
down_revision: Union[str, None] = "b6f2c5d8783b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cost_shortcuts",
        sa.Column("ui_position_index", sa.Integer(), nullable=True),
    )

    # populate ui_position_index with 1...N for each user
    op.execute(
        """
    WITH numbered AS (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY id) AS rn
        FROM cost_shortcuts
    )
    UPDATE cost_shortcuts
    SET ui_position_index = numbered.rn
    FROM numbered
    WHERE cost_shortcuts.id = numbered.id;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cost_shortcuts", "ui_position_index")
    # ### end Alembic commands ###
