"""empty message

Revision ID: ec492f05e5d5
Revises: 40c666676def
Create Date: 2024-09-24 11:06:47.470777

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec492f05e5d5"
down_revision: Union[str, None] = "40c666676def"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(), nullable=True))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "token")
    # ### end Alembic commands ###
