"""empty message

Revision ID: fce495e00337
Revises: 094b85889fa5
Create Date: 2025-06-24 16:37:04.822085

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fce495e00337"
down_revision: Union[str, None] = "094b85889fa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_metadata",
        sa.Column(
            "transactions_history",
            postgresql.ARRAY(sa.String(), dimensions=1),
            nullable=True,
        ),
    )
    op.drop_column("bank_metadata", "processed_transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bank_metadata",
        sa.Column(
            "processed_transactions",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("bank_metadata", "transactions_history")
    # ### end Alembic commands ###
