name: CI/CD

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

env:
  FBB__DATABASE__HOST: localhost
  FBB__DATABASE__PORT: 35432
  FBB__DATABASE__NAME: family_budget

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.12]

    services:
      postgres:
        image: postgres:16
        ports:
          - 35432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: family_budget

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run linter
        run: python -m flake8 .

      - name: Check formatting
        run: python -m black --check . && python -m isort --check .

      - name: Check types
        run: python -m mypy --check-untyped-defs .

      - name: Run tests
        run: python -m pytest -vvv -n 4 ./tests

  deployment:
    needs: build
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to the same server
        run: bash ${{ secrets.FAMBB_API_DEPLOY_SCRIPT_PATH }}
